import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, Check, ClipboardCheck, Eye, KeyRound, MapPin, Phone, Plus, ShieldCheck } from "lucide-react";
import type { Service } from "@/lib/services-data";
import { siteConfig } from "@/lib/config";
import { sectorsData } from "@/lib/secteurs-data";
import { Breadcrumbs } from "@/components/shared/breadcrumbs";
import ServiceJsonLd from "@/components/seo/service-json-ld";
import styles from "./qualified-agent-page.module.css";

const missions = [
  { icon: KeyRound, title: "Maîtriser les accès", text: "Accueil des visiteurs, contrôle des entrées et des sorties, vérification des autorisations et suivi des livraisons." },
  { icon: Eye, title: "Observer & prévenir", text: "Surveillance des zones sensibles, rondes de contrôle et détection des anomalies pour anticiper les situations à risque." },
  { icon: ShieldCheck, title: "Alerter & intervenir", text: "Application des consignes, première réponse aux incidents et coordination avec vos interlocuteurs et les secours si nécessaire." },
  { icon: ClipboardCheck, title: "Tracer & transmettre", text: "Main courante, remontées d’information et comptes rendus pour garder une vision claire de la vie de votre site." },
];
const complementary = [
  { title: "Rondes & interventions", slug: "agent-rondier", image: "/images/agent-rondier.webp", text: "Une surveillance mobile pour compléter la présence sur site." },
  { title: "Sécurité cynophile", slug: "agent-cynophile", image: "/images/agent-cynophile.webp", text: "Un binôme pour renforcer la détection et la dissuasion." },
  { title: "Sécurité incendie · SSIAP", slug: "agent-incendie-ssiap", image: "/images/securite-incendie.webp", text: "Des compétences dédiées à la prévention du risque incendie." },
];
const sectorSlugs: Record<string, string> = {
  "Sièges sociaux & bureaux": "sieges-sociaux-bureaux",
  "Sites industriels & entrepôts": "industrie-logistique",
  "Chantiers & BTP": "chantiers-sites-btp",
  "Retail & centres commerciaux": "luxe-retail-hotellerie",
  "Sites publics & institutionnels": "sites-sensibles-institutionnels",
  "Immobilier résidentiel": "immobilier-residentiel",
};

export function QualifiedAgentPage({ service }: { service: Service }) {
  const quoteHref = `/devis?service=${service.slug}`;
  const breadcrumbs = [{ label: "Accueil", href: "/" }, { label: "Services", href: "/services" }, { label: "Agent de sécurité qualifié", href: `/services/${service.slug}` }];
  const faq = [
    ...(service.page?.faqLong ?? []),
    { question: "Quels horaires de surveillance peut-on prévoir ?", answer: "Présence en journée, surveillance de nuit, week-ends ou renfort ponctuel : les horaires et les effectifs sont définis selon vos besoins et les disponibilités de nos équipes." },
    ...service.faq.filter(item => !item.question.includes("qualifications obligatoires")),
  ];
  return <div className={styles.page}>
    <ServiceJsonLd service={service} breadcrumbs={breadcrumbs} />
    <section className={styles.hero} aria-labelledby="aps-title">
      <div className={styles.heroVisual}><Image src="/images/securite-privee-gardiennage.webp" alt="Agent de sécurité en tenue, en surveillance sur site" fill priority sizes="(max-width: 767px) 100vw, 60vw" className="object-cover" /></div><div className={styles.heroShade} />
      <div className="premium-shell relative"><div className="pt-6"><Breadcrumbs items={breadcrumbs} variant="onDark" /></div>
        <div className={styles.heroCopy}><p className="premium-eyebrow text-[#d9c6a3]"><span className={styles.line} />Gardiennage & surveillance · APS</p><h1 id="aps-title">Agent de sécurité<br /><span className="premium-serif text-[#d9c6a3]">qualifié.</span></h1><p className={styles.heroLead}>Une présence attentive.<br />Votre quotidien en confiance.</p><p className={styles.heroText}>Protéger vos locaux, accueillir vos visiteurs, veiller sur vos équipes. Une sécurité humaine, préparée avec soin et encadrée sur le terrain.</p><div className="mt-8 flex flex-wrap items-center gap-6"><Link href={quoteHref} className="premium-button premium-button-gold">Étudier mon besoin <ArrowUpRight size={18} aria-hidden="true" /></Link><a href="#missions" className={styles.lightLink}>Découvrir les missions <ArrowDown size={16} aria-hidden="true" /></a></div></div>
        <div className={styles.heroFoot}><span>Prévenir. Protéger. Rassurer.</span><span className="flex items-center gap-2"><MapPin size={14} aria-hidden="true" />Yvelines & Île-de-France</span></div>
      </div>
    </section>
    <nav className={styles.navigation} aria-label="Dans cette prestation"><div className="premium-shell"><a href="#missions">01 — Les missions</a><a href="#engagements">02 — Nos engagements</a><a href="#methode">03 — Le déploiement</a><a href="#questions">04 — Vos questions</a><Link href={quoteHref}>Votre devis <ArrowUpRight size={15} aria-hidden="true" /></Link></div></nav>
    <section id="missions" className="premium-shell premium-section" aria-labelledby="missions-title">
      <div className={styles.intro}><div><p className="premium-eyebrow text-muted-foreground">01 — Au cœur de votre site</p><h2 id="missions-title" className="premium-title mt-5">La vigilance au quotidien.<br /><span className="premium-serif">La sérénité en plus.</span></h2></div><div><p className={styles.introLead}>Un agent qui connaît vos lieux, vos usages et vos priorités.</p><p className={styles.bodyText}>Le dispositif s’adapte à votre activité : présence en journée, surveillance nocturne, week-ends ou renfort ponctuel. Chaque mission repose sur des consignes précises et un interlocuteur identifié.</p></div></div>
      <div className={styles.missions}>{missions.map(({icon: Icon, title, text}, i) => <article key={title}><div className={styles.missionTop}><Icon size={27} strokeWidth={1.3} aria-hidden="true" /><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div>
      <div className={styles.scope}><ShieldCheck size={23} strokeWidth={1.4} className="shrink-0 text-[#9c8056]" aria-hidden="true" /><p><strong>Un cadre clair, dès le départ.</strong> Les missions, horaires, points de contrôle et procédures d’alerte sont définis avec vous avant la prise de poste.</p></div>
    </section>
    <section id="engagements" className={styles.commitment} aria-labelledby="commitment-title"><div className="premium-shell premium-section"><div className={styles.commitmentGrid}><div className={styles.portrait}><Image src="/images/services/services-securite-privee.avif" alt="Professionnel de la sécurité en costume" fill sizes="(max-width: 767px) 100vw, 45vw" className="object-cover object-top" /><div className={styles.portraitCaption}><span>Basic Protection Privée</span><p>Le sérieux dans la posture.<br /><em>L’exigence dans l’action.</em></p></div></div><div className={styles.commitmentCopy}><p className="premium-eyebrow text-muted-foreground">02 — L’exigence Basic Protection</p><h2 id="commitment-title" className="premium-title mt-5">La bonne personne.<br /><span className="premium-serif">Le bon encadrement.</span></h2><p className={styles.bodyText}>La qualité d’une présence se construit en amont et se cultive chaque jour. Nous associons sélection des profils, préparation au site et management de proximité.</p><ul className={styles.checks}>{(service.whyUs ?? []).map(item => <li key={item.title}><Check size={17} aria-hidden="true" /><div><h3>{item.title}</h3><p>{item.description}</p></div></li>)}</ul></div></div></div></section>
    <section className="premium-shell premium-section" aria-labelledby="benefits-title"><div className={styles.intro}><div><p className="premium-eyebrow text-muted-foreground">Ce que cela change pour vous</p><h2 id="benefits-title" className="premium-title mt-5">Une protection visible.<br /><span className="premium-serif">Des bénéfices concrets.</span></h2></div><p className={styles.bodyText}>Un dispositif pensé pour protéger vos biens et vos équipes, tout en préservant la fluidité de votre activité.</p></div><div className={styles.benefits}>{service.benefits.map((benefit, i) => <article key={benefit.title}><span>0{i+1}</span><h3>{benefit.title}</h3><p>{benefit.description}</p></article>)}</div></section>
    <section id="methode" className="premium-dark premium-section" aria-labelledby="method-title"><div className="premium-shell"><div className={styles.intro}><div><p className="premium-eyebrow text-[#d9c6a3]">03 — Une mission bien préparée</p><h2 id="method-title" className="premium-title mt-5">De votre premier besoin<br /><span className="premium-serif text-[#d9c6a3]">au suivi sur le terrain.</span></h2></div><p className="max-w-sm text-sm leading-7 text-slate-300">Un déploiement en quatre étapes, pour construire un dispositif cohérent et le faire évoluer avec votre activité.</p></div><ol className={styles.steps}>{service.method.steps.map((step, i) => <li key={step.title}><span>0{i+1}</span><h3>{step.title}</h3><p>{step.description}</p></li>)}</ol><div className={styles.methodFooter}><span>Des consignes claires. Un suivi régulier. Un interlocuteur à vos côtés.</span><Link href={quoteHref} className="premium-text-link text-[#d9c6a3]">Préparer votre mission <ArrowUpRight size={17} aria-hidden="true" /></Link></div></div></section>
    <section className="premium-shell premium-section" aria-labelledby="sectors-title"><div className={styles.intro}><div><p className="premium-eyebrow text-muted-foreground">Vos lieux, nos missions</p><h2 id="sectors-title" className="premium-title mt-5">À chaque environnement,<br /><span className="premium-serif">la juste attention.</span></h2></div><p className={styles.bodyText}>De l’accueil d’un siège social à la surveillance d’un chantier, la posture et les consignes s’adaptent aux réalités de votre site.</p></div><div className={styles.sectors}>{service.sectors.map(sector => { const definition = sectorsData.find(s => s.slug === sectorSlugs[sector.name]); return definition ? <Link key={sector.name} href={`/secteurs/${definition.slug}`}>{sector.name}<ArrowUpRight size={18} aria-hidden="true" /></Link> : <span key={sector.name}>{sector.name}</span>; })}</div></section>
    <section id="questions" className={styles.faqSection} aria-labelledby="faq-title"><div className="premium-shell premium-section"><div className={styles.faqGrid}><div><p className="premium-eyebrow text-muted-foreground">04 — Avant de commencer</p><h2 id="faq-title" className="premium-title mt-5">Vos questions.<br /><span className="premium-serif">Nos réponses.</span></h2><p className={styles.bodyText}>Une situation particulière ? Parlons-en directement.</p><a href={`tel:${siteConfig.contact.phoneE164}`} className="premium-text-link mt-7"><Phone size={16} aria-hidden="true" />{siteConfig.contact.phone}</a></div><div>{faq.map(item => <details key={item.question} className={styles.question}><summary>{item.question}<Plus size={18} aria-hidden="true" /></summary><p>{item.answer}</p></details>)}</div></div></div></section>
    <section className="premium-shell premium-section" aria-labelledby="related-title"><div className={styles.relatedHead}><div><p className="premium-eyebrow text-muted-foreground">Aller plus loin</p><h2 id="related-title" className="premium-title mt-5">Une protection<br /><span className="premium-serif">qui se complète.</span></h2></div><Link href="/services" className="premium-text-link">Toutes nos expertises <ArrowUpRight size={17} aria-hidden="true" /></Link></div><div className={styles.related}>{complementary.map(item => <Link key={item.slug} href={`/services/${item.slug}`} className={styles.relatedCard}><div className={styles.relatedImage}><Image src={item.image} alt={item.title} fill sizes="(max-width: 639px) 100vw, 33vw" className="object-cover" /><span><ArrowUpRight size={20} aria-hidden="true" /></span></div><h3>{item.title}</h3><p>{item.text}</p></Link>)}</div></section>
    <section className={styles.contact} aria-labelledby="contact-title"><div className="premium-shell"><div className={styles.contactInner}><div><p className="premium-eyebrow text-[#d9c6a3]">Votre site mérite une attention particulière</p><h2 id="contact-title" className="premium-title mt-5">Confiez-nous votre sécurité.<br /><span className="premium-serif text-[#d9c6a3]">Concentrez-vous sur l’essentiel.</span></h2><p>Précisez votre lieu, vos horaires et vos priorités.<br />Construisons un dispositif à votre mesure.</p></div><div className="flex flex-col items-start gap-6"><Link href={quoteHref} className="premium-button premium-button-gold">Demander mon devis <ArrowUpRight size={18} aria-hidden="true" /></Link><a href={`tel:${siteConfig.contact.phoneE164}`} className={styles.lightLink}><Phone size={16} aria-hidden="true" />{siteConfig.contact.phone}</a></div></div></div></section>
  </div>;
}
