import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { ArrowDown, ArrowUpRight, MapPin, Phone, Plus, ShieldCheck } from "lucide-react";
import { locationsData } from "@/lib/locations-data";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { siteConfig } from "@/lib/config";
import LocationJsonLd from "@/components/seo/location-json-ld";
import { getCitiesByDeptCodeCached } from "@/lib/cities-helpers";
import { deptCodeFromZoneSlug } from "@/lib/zones-helpers";

type PageProps = { params: Promise<{ slug: string }> };
function getVisual(imageId: string) {
  const image = PlaceHolderImages.find(image => image.id === imageId);
  if (image?.imageUrl.startsWith("/") || image?.imageUrl.startsWith("https://")) return { src: image.imageUrl, alt: "", local: true };
  return { src: "/images/securite-privee-gardiennage.webp", alt: "Un professionnel de la sécurité privée", local: false };
}
export async function generateStaticParams() { return locationsData.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const location = locationsData.find(location => location.slug === slug);
  if (!location) return {};
  const url = `${siteConfig.url}/zones/${slug}`;
  const visual = getVisual(location.heroImageId);
  return { title: location.title, description: location.description, keywords: location.keywords, alternates: { canonical: url }, openGraph: { title: location.title, description: location.description, url, siteName: siteConfig.name, type: "website", images: [{ url: visual.src }] }, twitter: { card: "summary_large_image", title: location.title, description: location.description, images: [visual.src] } };
}

export default async function LocationPage({ params }: PageProps) {
  const { slug } = await params;
  const location = locationsData.find(location => location.slug === slug);
  if (!location) notFound();
  const name = location.name.replace(/\s*\(\d+\)/, "");
  const code = deptCodeFromZoneSlug(slug) || location.name.match(/\((\d+)\)/)?.[1] || "";
  const visual = getVisual(location.heroImageId);
  const cities = getCitiesByDeptCodeCached(code).map(city => ({ name: city.title.replace(/^Sécurité Privée\s*/i, ""), href: `/villes/${city.slug}` })).sort((a, b) => a.name.localeCompare(b.name, "fr"));
  const availableCities = cities.length ? cities : location.mainCities;
  const breadcrumbs = [{ label: "Accueil", href: "/" }, { label: "Notre présence", href: "/zones" }, { label: location.name, href: `/zones/${slug}` }];
  const quoteHref = `/devis?zone=${slug}`;

  return <>
    <LocationJsonLd location={location} breadcrumbs={breadcrumbs} />
    <section className="territory-hero" aria-labelledby="territory-title"><div className="territory-visual"><Image src={visual.src} alt={visual.alt} fill priority sizes="(max-width: 1023px) 100vw, 55vw" className="object-cover" /><div className="territory-shade" /></div><div className="premium-shell relative z-10"><nav aria-label="Fil d’Ariane" className="flex flex-wrap gap-3 pt-8 text-[11px] text-white/60"><Link href="/" className="hover:text-white">Accueil</Link><span aria-hidden="true">/</span><Link href="/zones" className="hover:text-white">Notre présence</Link><span aria-hidden="true">/</span><span aria-current="page">{location.name}</span></nav><div className="territory-hero-copy"><p className="premium-eyebrow text-[#d9c6a3]">Sécurité privée · Département {code}</p><h1 id="territory-title" className="mt-7 font-headline text-[clamp(2.6rem,5.7vw,5.5rem)] font-medium leading-[1.06] tracking-[-0.05em]">{name}.<br /><span className="premium-serif text-[#d9c6a3]">Protéger l’essentiel.</span></h1><p className="mt-7 max-w-lg text-sm leading-relaxed text-white/70">{location.description}</p><div className="mt-9 flex flex-wrap items-center gap-7"><Link href={quoteHref} className="premium-button premium-button-gold">Parlons de votre projet <ArrowUpRight size={17} /></Link><a href="#villes" className="flex items-center gap-3 border-b border-white/30 pb-2 text-xs text-white/80">Trouver votre ville <ArrowDown size={15} /></a></div></div><div className="territory-signature" aria-hidden="true"><span>{code}</span><p>{name} · Île-de-France</p></div></div></section>
    <nav aria-label="Dans cette page" className="border-b bg-card"><div className="premium-shell flex flex-wrap gap-x-9 gap-y-4 py-5 text-xs text-muted-foreground">{[["01", "Le territoire", "#territoire"], ["02", "Nos expertises", "#expertises"], ["03", "Vos villes", "#villes"], ["04", "Vos questions", "#questions"]].map(([number, label, href]) => <a key={href} href={href} className="flex items-center gap-3 hover:text-foreground"><span className="text-[10px] text-[#9c8056]">{number}</span>{label}</a>)}</div></nav>

    <section id="territoire" className="premium-shell premium-section"><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20"><div><p className="premium-eyebrow text-[#9c8056]">01 — Comprendre votre territoire</p><h2 className="premium-title mt-5">Une présence adaptée.<br /><span className="premium-serif">À chaque environnement.</span></h2></div><div><h3 className="font-headline text-2xl font-medium leading-snug tracking-tight">{location.intro.title}</h3><div className="mt-6 text-sm leading-loose text-muted-foreground [&_p+p]:mt-4" dangerouslySetInnerHTML={{ __html: location.intro.content }} /></div></div>
    {location.useCases.length > 0 && <div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{location.useCases.map((useCase, index) => <article key={useCase.title} className="border-t pt-6"><span className="text-xs text-[#9c8056]">0{index + 1} / Sur le terrain</span><h3 className="mt-5 font-headline text-xl font-medium tracking-tight">{useCase.title}</h3><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{useCase.content}</p></article>)}</div>}</section>

    <section id="expertises" className="premium-dark premium-section"><div className="premium-shell"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="premium-eyebrow text-[#d9c6a3]">02 — Les moyens de votre sérénité</p><h2 className="premium-title mt-5 text-white">Le bon dispositif.<br /><span className="premium-serif text-[#d9c6a3]">Pour les bons enjeux.</span></h2></div><p className="max-w-sm text-sm leading-relaxed text-white/60">De la présence quotidienne à la mission ponctuelle, les moyens sont définis selon vos accès, vos horaires et votre activité.</p></div><div className="mt-12 grid gap-x-10 md:grid-cols-2 lg:grid-cols-3">{location.services.map((service, index) => <Link key={service.href} href={service.href} className="territory-service group"><div className="flex items-center justify-between text-[#d9c6a3]"><span className="text-xs">0{index + 1}</span><ArrowUpRight size={20} strokeWidth={1.3} className="transition-transform group-hover:translate-x-1" /></div><h3 className="mt-7 font-headline text-xl font-medium tracking-tight">{service.title}</h3><p className="mt-4 text-sm leading-relaxed text-white/60">{service.description}</p><span className="mt-auto block pt-6 text-[11px] text-[#d9c6a3]">Découvrir cette expertise</span></Link>)}</div></div></section>

    <section id="villes" className="premium-shell premium-section"><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20"><div><p className="premium-eyebrow text-[#9c8056]">03 — Au plus près de vous</p><h2 className="premium-title mt-5">Votre ville.<br /><span className="premium-serif">Notre attention.</span></h2><p className="mt-6 max-w-sm text-sm leading-relaxed text-muted-foreground">Explorez nos interventions locales pour découvrir les besoins et les prestations adaptés à votre environnement.</p><div className="mt-8 flex items-center gap-4 border-t pt-6"><MapPin size={20} className="text-[#9c8056]" /><p className="text-sm">{name} <span className="text-muted-foreground">· {code}</span></p></div></div><div><div className="grid gap-x-7 sm:grid-cols-2">{availableCities.map(city => city.href && city.href !== "#" ? <Link key={city.href} href={city.href} className="territory-city group"><span>{city.name}</span><ArrowUpRight size={16} className="shrink-0 text-[#9c8056] transition-transform group-hover:translate-x-1" /></Link> : <p key={city.name} className="territory-city">{city.name}</p>)}</div><p className="mt-7 text-xs leading-relaxed text-muted-foreground">Votre commune n’apparaît pas ? <Link href="/contact" className="underline underline-offset-4 hover:text-foreground">Contactez notre équipe</Link> pour étudier votre projet.</p></div></div></section>

    {location.whyUs.length > 0 && <section className="border-y bg-card py-16 md:py-20"><div className="premium-shell"><div className="flex items-center gap-3"><ShieldCheck size={20} strokeWidth={1.3} className="text-[#9c8056]" /><p className="premium-eyebrow text-muted-foreground">L’exigence Basic Protection</p></div><div className="mt-9 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{location.whyUs.map(item => <div key={item.title}><h2 className="font-headline text-lg font-medium tracking-tight">{item.title}</h2><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{item.description}</p></div>)}</div></div></section>}
    {location.faq.length > 0 && <section id="questions" className="premium-shell premium-section"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20"><div><p className="premium-eyebrow text-[#9c8056]">04 — Vos questions</p><h2 className="premium-title mt-5">Des repères clairs.<br /><span className="premium-serif">Avant de commencer.</span></h2><p className="mt-6 max-w-sm text-sm leading-relaxed text-muted-foreground">Organisation, périmètre et préparation de votre mission : les réponses pour avancer.</p></div><div>{location.faq.map(item => <details key={item.question} className="contact-faq group border-b first:border-t"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-6 font-headline text-lg tracking-tight">{item.question}<Plus size={17} className="shrink-0 text-[#9c8056] transition-transform group-open:rotate-45" /></summary><p className="pb-6 text-sm leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div></div></section>}

    <section className="premium-dark py-16 md:py-24"><div className="premium-shell flex flex-col justify-between gap-9 lg:flex-row lg:items-center"><div><p className="premium-eyebrow text-[#d9c6a3]">Votre projet · {name}</p><h2 className="premium-title mt-5 text-white">Un lieu à protéger.<br /><span className="premium-serif text-[#d9c6a3]">Une conversation à commencer.</span></h2><p className="mt-6 max-w-lg text-sm leading-relaxed text-white/60">Présentez-nous votre site, vos horaires et vos contraintes. Construisons une réponse adaptée à votre réalité.</p></div><div className="flex shrink-0 flex-col items-start gap-6"><Link href={quoteHref} className="premium-button premium-button-gold">Étudier votre projet <ArrowUpRight size={18} /></Link><a href={`tel:${siteConfig.contact.phoneE164}`} className="flex items-center gap-3 text-sm text-white/80"><Phone size={16} />{siteConfig.contact.phone}</a></div></div></section>
    <section className="premium-shell py-12 md:py-16"><div className="flex flex-wrap items-center justify-between gap-5"><h2 className="font-headline text-xl tracking-tight">Une présence dans toute l’Île-de-France.</h2><Link href="/zones" className="premium-text-link">Tous nos territoires <ArrowUpRight size={16} /></Link></div><nav aria-label="Autres départements" className="mt-7 flex flex-wrap gap-x-7 gap-y-4 border-t pt-6">{locationsData.filter(other => other.slug !== slug).map(other => <Link key={other.slug} href={`/zones/${other.slug}`} className="text-xs text-muted-foreground hover:text-foreground">{other.name}</Link>)}</nav></section>
  </>;
}
