import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, ClipboardCheck, Eye, MapPin, Phone, ShieldCheck } from "lucide-react";
import { siteConfig } from "@/lib/config";

const title = "À propos — L’exigence de la sérénité";
const description = "Découvrez Basic Protection Privée, agence de sécurité à Plaisir : une approche humaine, des dispositifs sur mesure et un suivi rigoureux en Île-de-France.";
export const metadata: Metadata = {
  title, description,
  alternates: { canonical: `${siteConfig.url}/a-propos` },
  openGraph: { title, description, url: `${siteConfig.url}/a-propos`, siteName: siteConfig.name, type: "website", images: [{ url: "/images/a-propos-basic-protection.webp", alt: "Basic Protection Privée — une relation de confiance" }] },
  twitter: { card: "summary_large_image", title, description, images: ["/images/a-propos-basic-protection.webp"] },
};

const values = [
  { title: "La rigueur.", subtitle: "Dans chaque détail.", icon: ShieldCheck, text: "Des consignes précises, des équipes préparées et une mission encadrée. Nous accordons autant d’importance à la préparation qu’à la présence sur le terrain.", detail: "Préparer · Encadrer · Contrôler" },
  { title: "La discrétion.", subtitle: "Dans chaque présence.", icon: Eye, text: "Une posture adaptée à vos lieux, à vos publics et à votre activité. Protéger efficacement, tout en respectant le fonctionnement et l’image de votre organisation.", detail: "Observer · S’adapter · Préserver" },
  { title: "La confiance.", subtitle: "Dans chaque échange.", icon: ClipboardCheck, text: "Un dialogue clair, des informations utiles et un suivi régulier. Vous comprenez le dispositif mis en place et vous gardez une visibilité sur la mission.", detail: "Écouter · Informer · Accompagner" },
];
const steps = [
  { title: "Écouter avant d’agir", text: "Nous prenons le temps de comprendre votre activité, vos horaires, vos accès et les points sensibles de votre environnement.", result: "Un besoin clairement défini" },
  { title: "Concevoir le bon dispositif", text: "Nous déterminons les moyens humains, les postes et les procédures adaptés. Les consignes et les modalités de suivi sont formalisées.", result: "Une proposition lisible et adaptée" },
  { title: "Être présents, avec méthode", text: "Les équipes sont briefées sur leur mission. L’encadrement accompagne la mise en place et les ajustements nécessaires sur le terrain.", result: "Une exécution encadrée" },
  { title: "Suivre et faire progresser", text: "Les remontées terrain et vos retours permettent de faire le point sur la prestation et d’adapter le dispositif dans la durée.", result: "Un suivi qui fait la différence" },
];

export default function AboutPage() {
  return (
    <>
      <section className="about-intro border-b" aria-labelledby="about-title">
        <div className="premium-shell">
          <nav aria-label="Fil d’Ariane" className="flex items-center gap-3 pt-8 text-[11px] text-muted-foreground"><Link href="/" className="hover:text-foreground">Accueil</Link><span aria-hidden="true">/</span><span aria-current="page">À propos</span></nav>
          <div className="about-hero-grid">
            <div className="about-hero-copy"><p className="premium-eyebrow text-[#9c8056]">Basic Protection Privée · Notre identité</p><h1 id="about-title" className="mt-7 font-headline text-[clamp(2.5rem,4.3vw,4.3rem)] font-medium leading-[1.06] tracking-[-0.055em]">La sécurité est<br />notre métier.<br /><span className="premium-serif">La confiance,<br />notre engagement.</span></h1><p className="mt-8 max-w-md text-base leading-relaxed text-muted-foreground">Une agence à taille humaine, portée par une conviction : votre tranquillité se construit par la qualité de notre présence.</p><a href="#engagements" className="premium-text-link mt-9">Découvrir ce qui nous anime <ArrowDown size={16} /></a></div>
            <div className="relative"><div className="about-hero-photo"><Image src="/images/a-propos-basic-protection.webp" alt="Une poignée de main, symbole d’une relation de confiance" fill priority sizes="(max-width: 1023px) 100vw, 50vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#101c2d]/60 via-transparent to-transparent" /><div className="absolute bottom-7 left-7 right-7 text-white"><p className="premium-eyebrow text-white/70">Notre façon d’être</p><p className="mt-3 font-headline text-2xl tracking-tight">Un partenaire.<br />Avant tout.</p></div></div><div className="about-image-note"><span className="h-px w-7 bg-[#b79c73]" /><span>Rigueur. Discrétion. Confiance.</span></div></div>
          </div>
        </div>
      </section>

      <section className="premium-shell premium-section" aria-labelledby="conviction-title"><div className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr] lg:gap-24"><div><p className="premium-eyebrow text-muted-foreground">01 — Notre conviction</p><h2 id="conviction-title" className="mt-6 font-headline text-xl font-medium leading-snug">Bien protéger,<br />c’est d’abord bien comprendre.</h2></div><div><p className="font-headline text-[clamp(1.6rem,2.8vw,2.6rem)] font-medium leading-snug tracking-[-0.035em]">Derrière chaque lieu à sécuriser,<br className="hidden md:block" /> il y a des personnes, une activité<br className="hidden md:block" /> et une confiance à préserver.</p><div className="mt-8 grid gap-6 text-sm leading-relaxed text-muted-foreground sm:grid-cols-2"><p>Basic Protection Privée accompagne les entreprises, commerces, gestionnaires de sites et organisateurs d’événements en Île-de-France. Chaque mission commence par une lecture attentive de votre environnement.</p><p>Notre rôle : transformer vos besoins en une organisation concrète. Des moyens adaptés, des consignes compréhensibles et un suivi qui vous permet d’avancer sereinement.</p></div></div></div></section>

      <section id="engagements" className="premium-dark premium-section" aria-labelledby="values-title"><div className="premium-shell"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="premium-eyebrow text-[#d9c6a3]">02 — Ce qui nous anime</p><h2 id="values-title" className="premium-title mt-6 text-white">Trois exigences.<br /><span className="premium-serif text-[#d9c6a3]">Une même ligne de conduite.</span></h2></div><p className="max-w-sm text-sm leading-relaxed text-white/60">Des principes qui prennent leur sens dans la préparation, l’intervention et la relation avec vous.</p></div><div className="mt-14 grid gap-10 md:grid-cols-3 md:gap-9">{values.map(({ title: valueTitle, subtitle, text, detail, icon: Icon }, index) => <article key={valueTitle} className="flex flex-col border-t border-white/20 pt-7"><div className="flex items-center justify-between text-[#d9c6a3]"><span className="text-xs">0{index + 1}</span><Icon size={25} strokeWidth={1.2} aria-hidden="true" /></div><h3 className="mt-9 font-headline text-3xl font-medium tracking-tight">{valueTitle}</h3><p className="premium-serif mt-1 text-xl text-[#d9c6a3]">{subtitle}</p><p className="mt-6 text-sm leading-relaxed text-white/65">{text}</p><p className="mt-auto pt-9 text-[10px] uppercase tracking-[0.13em] text-white/45">{detail}</p></article>)}</div></div></section>

      <section className="premium-shell premium-section" aria-labelledby="method-title"><div className="grid gap-12 lg:grid-cols-[0.85fr_1.15fr] lg:gap-24"><div><p className="premium-eyebrow text-muted-foreground">03 — Notre façon de travailler</p><h2 id="method-title" className="premium-title mt-6">Une présence humaine.<br /><span className="premium-serif">Une méthode précise.</span></h2><p className="mt-6 max-w-sm leading-relaxed text-muted-foreground">Une prestation de sécurité se prépare, s’encadre et se suit. Nous vous accompagnons à chacune de ces étapes.</p><Link href="/services" className="premium-text-link mt-8">Explorer nos expertises <ArrowUpRight size={17} /></Link></div><ol>{steps.map((step, index) => <li key={step.title} className="grid grid-cols-[2rem_1fr] gap-5 border-t py-7 sm:gap-8"><span className="pt-1 font-headline text-lg text-[#9c8056]">0{index + 1}</span><div><h3 className="font-headline text-xl font-medium tracking-tight">{step.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{step.text}</p><p className="mt-4 inline-flex items-center gap-2 text-xs font-medium"><span className="h-px w-4 bg-[#b79c73]" />{step.result}</p></div></li>)}</ol></div></section>

      <section className="border-y bg-card premium-section" aria-labelledby="presence-title"><div className="premium-shell grid gap-10 lg:grid-cols-2 lg:items-center lg:gap-20"><div className="relative aspect-[5/4] overflow-hidden bg-muted"><Image src="/images/zones/securite-privee-hauts-de-seine.webp" alt="La Défense, au cœur du territoire francilien" fill sizes="(max-width: 1023px) 100vw, 50vw" className="object-cover" /><div className="absolute bottom-0 left-0 flex items-center gap-3 bg-[#101c2d] px-6 py-5 text-white"><MapPin size={17} className="text-[#d9c6a3]" /><span className="text-sm">Notre terrain : l’Île-de-France.</span></div></div><div><p className="premium-eyebrow text-muted-foreground">04 — Notre ancrage</p><h2 id="presence-title" className="premium-title mt-6">À Plaisir.<br /><span className="premium-serif">À vos côtés.</span></h2><p className="mt-6 leading-relaxed text-muted-foreground">Installés dans les Yvelines, nous intervenons dans les huit départements d’Île-de-France. Cette implantation nous permet d’accompagner des environnements variés, des sites résidentiels aux lieux de réception, des bureaux aux chantiers.</p><div className="mt-7 border-l border-[#b79c73] pl-5"><p className="text-sm font-medium">{siteConfig.name}</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{siteConfig.business.address.street}<br />{siteConfig.business.address.postalCode} {siteConfig.business.address.city}</p></div><Link href="/zones" className="premium-text-link mt-8">Découvrir notre présence <ArrowUpRight size={17} /></Link></div></div></section>

      <section className="premium-shell py-16 text-center md:py-24" aria-label="Notre engagement"><p className="premium-eyebrow justify-center text-[#9c8056]">L’exigence de la sérénité</p><p className="mx-auto mt-7 max-w-4xl font-headline text-[clamp(1.8rem,3.8vw,3.5rem)] font-medium leading-tight tracking-[-0.04em]">Être présents pour que vous puissiez<br className="hidden md:block" /><span className="premium-serif"> vous consacrer à l’essentiel.</span></p></section>
      <section className="premium-dark border-b border-white/10 py-16 md:py-24"><div className="premium-shell flex flex-col justify-between gap-10 lg:flex-row lg:items-center"><div><p className="premium-eyebrow text-[#d9c6a3]">Faisons connaissance</p><h2 className="premium-title mt-5 text-white">La confiance commence<br />par une conversation.</h2><p className="mt-5 max-w-lg text-sm leading-relaxed text-white/60">Parlez-nous de votre site, de votre événement ou de vos enjeux. Construisons ensemble une réponse adaptée.</p></div><div className="flex shrink-0 flex-col items-start gap-6"><Link href="/contact" className="premium-button premium-button-gold">Rencontrons-nous <ArrowUpRight size={18} /></Link><a href={`tel:${siteConfig.contact.phoneE164}`} className="flex items-center gap-3 text-sm text-white/80 hover:text-[#d9c6a3]"><Phone size={16} />{siteConfig.contact.phone}</a></div></div></section>
    </>
  );
}
